use ElSalvadorRegistroScouts;


INSERT INTO Secciones(Nombre, Descripcion,baja,rangoInicio,rangoFin,sexo) VALUES
					('Lobato','Miembros varones con hasta 10 años cumplidos.',1,1,10,'m'),
					('Lobezna','Miembros hembras con hasta 10 años cumplidos.',1,1,10,'f'),
					('Scout masculino','Miembros varones entre los 11 y 14 años cumplidos.',1,11,14,'m'),
					('Scout femenino','Miembros hembras entre los 11 y 14 años cumplidos.',1,11,14,'f'),
					('Caminante masculino','Miembros varones entre los 15 y 17 años cumplidos.',1,15,17,'m'),
					('Caminante femenino','Miembros hembras entre los 15 y 17 años cumplidos.',1,15,17,'f'),
					('Rover masculino','Miembros varones entre los 18 y 22 años cumplidos.',1,18,22,'m'),
					('Rover femenino','Miembros hembras entre los 18 y 22 años cumplidos.',1,18,22,'f'),
					('Scouter masculino','Miembros varones mayores de 22 años.',1,23,null,'m'),
					('Scouter femenino','Miembros hembras mayores de 22 años.',1,23,null,'f'),
					('Padre Scout','Miembro reconocido.',1,23,null,'m')

INSERT INTO Religion(nombre,baja) VALUES
					('Cristiano Católico',1),
					('Cristiano Evangélico',1),
					('Testigo de Jehová',1),
					('Budista',1),
					('Ateo',1)

INSERT INTO Escolaridad(grado,baja) VALUES
					('Primer ciclo',1),
					('Segundo ciclo',1),
					('Tercer ciclo',1),
					('Bachiller',1),
					('Universitario',1)

INSERT INTO EstadoCivil(estadoCivil,baja) VALUES
					('Soltero',1),
					('Casado',1),
					('Divorciado',1),
					('Viudo',1)


INSERT INTO Provincias(nombre,baja,clave,idRegion) VALUES
					('Provincia Occidente',1,'OCC',1),
					('Provincia San Salvador',1,'SSV',1),
					('Provincia Central',1,'CNT',1),
					('Provincia Oriente',1,'ORI',1),
					('Provincia Paracentral',1,'PRC',1)

INSERT INTO Distritos(nombre,numero,baja,idProvincia) VALUES
					('Distrito Santa Ana',1,1,1),
					('Distrito Ahuachapán',2,1,1),
					('Distrito Anastacio Aquino',1,2,1),
					('Distrito Atonal',2,2,1),
					('Distrito Cordillera del Bálsamo',1,3,1),
					('Distrito Atilio Mónico',2,3,1)

INSERT INTO Localidades(nombre, domicilioCorrespondencia, baja) VALUES
					('Casa Scout', 'Avenida Baden Powell, 281, San Salvador',1)


SET IDENTITY_INSERT [dbo].[Perfiles] ON 
INSERT [dbo].[Perfiles] ([idPerfil], [nombre], [baja]) VALUES (1, N'Administrador', 1)
INSERT [dbo].[Perfiles] ([idPerfil], [nombre], [baja]) VALUES (2, N'Direccion nacional', 1)
INSERT [dbo].[Perfiles] ([idPerfil], [nombre], [baja]) VALUES (3, N'Consulta nacional', 1)
INSERT [dbo].[Perfiles] ([idPerfil], [nombre], [baja]) VALUES (4, N'Presidente de provincia', 1)
INSERT [dbo].[Perfiles] ([idPerfil], [nombre], [baja]) VALUES (5, N'Provincia consulta', 1)
INSERT [dbo].[Perfiles] ([idPerfil], [nombre], [baja]) VALUES (6, N'Jefe de grupo', 1)
INSERT [dbo].[Perfiles] ([idPerfil], [nombre], [baja]) VALUES (7, N'Consulta grupo', 1)
SET IDENTITY_INSERT [dbo].[Perfiles] OFF
SET IDENTITY_INSERT [dbo].[Usuarios] ON 


INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'Ahuachapán', N'SV-AH', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'Santa Ana', N'SV-SA', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'Sonsonate', N'SV-SO', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'La Libertad', N'SV-LI', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'Chalatenango', N'SV-CH', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'San Salvador', N'SV-SS', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'Cuscatlán', N'SV-CU', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'La Paz', N'SV-PA', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'Cabañas', N'SV-CA', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'San Vicente', N'SV-SV', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'Usulután', N'SV-US', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'Morazán', N'SV-MO', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'San Miguel', N'SV-SM', 1)
INSERT INTO Departamentos(nombre, clave, baja) VALUES (N'La Unión', N'SV-UN', 1)


INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ahuachapán', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jujutla', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Atiquizaya', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Concepción de Ataco', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Refugio', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Guaymango', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Apaneca', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Francisco Menéndez', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Lorenzo (Ahuachapán)', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Pedro Puxtla', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tacuba', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Turín', 1, 1)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Candelaria de la Frontera', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Chalchuapa', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Coatepeque', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Congo', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Porvenir', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Masahuat', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Metapán', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Antonio Pajonal', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Sebastián Salitrillo', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Ana', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Rosa Guachipilín', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santiago de la Frontera', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Texistepeque', 1, 2)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Acajutla', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Armenia', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Caluco', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Cuisnahuat', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Izalco', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Juayúa', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nahuizalco', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nahulingo', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Salcoatitán', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Antonio del Monte', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Julián', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Catarina Masahuat', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Isabel Ishuatán', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santo Domingo de Guzmán', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Sonsonate', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Sonzacate', 1, 3)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Alegría', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Berlín', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'California', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Concepción Batres', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Triunfo', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ereguayquín', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Estanzuelas', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jiquilisco', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jucuapa', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jucuarán', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Mercedes Umaña', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nueva Granada', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ozatlán', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Puerto El Triunfo', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Agustín', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Buenaventura', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Dionisio', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Francisco Javier', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Elena', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa María', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santiago de María', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tecapán', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Usulután', 1, 11)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Carolina', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Chapeltique', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Chinameca', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Chirilagua', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ciudad Barrios', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Comacarán', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Tránsito', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Lolotique', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Moncagua', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nueva Guadalupe', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nuevo Edén de San Juan', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Quelepa', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Antonio del Mosco', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Gerardo', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Jorge', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Luis de la Reina', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Miguel', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Rafael Oriente', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Sesori', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Uluazapa', 1, 13)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Arambala', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Cacaopera', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Chilanga', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Corinto', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Delicias de Concepción', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Divisadero', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Rosario (Morazán)', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Gualococti', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Guatajiagua', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Joateca', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jocoaitique', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jocoro', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Lolotiquillo', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Meanguera', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Osicala', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Perquín', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Carlos', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Fernando (Morazán)', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Francisco Gotera', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Isidro (Morazán)', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Simón', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Sensembra', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Sociedad', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Torola', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Yamabal', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Yoloaiquín', 1, 12)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'La Unión', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Alejo', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Yucuaiquín', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Conchagua', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Intipucá', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San José', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Carmen (La Unión)', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Yayantique', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Bolívar', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Meanguera del Golfo', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Rosa de Lima', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Pasaquina', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Anamoros', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nueva Esparta', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Sauce', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Concepción de Oriente', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Polorós', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Lislique', 1, 14)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Antiguo Cuscatlán', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Chiltiupán', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ciudad Arce', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Colón', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Comasagua', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Huizúcar', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jayaque', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jicalapa', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'La Libertad', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Tecla', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nuevo Cuscatlán', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Juan Opico', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Quezaltepeque', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Sacacoyo', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San José Villanueva', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Matías', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Pablo Tacachico', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Talnique', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tamanique', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Teotepeque', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tepecoyo', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Zaragoza', 1, 4)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Agua Caliente', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Arcatao', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Azacualpa', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Cancasque', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Chalatenango', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Citalá', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Comapala', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Concepción Quezaltepeque', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Dulce Nombre de María', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Carrizal', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Paraíso', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'La Laguna', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'La Palma', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'La Reina', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Las Vueltas', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nueva Concepción', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nueva Trinidad', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nombre de Jesús', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ojos de Agua', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Potonico', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Antonio de la Cruz', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Antonio Los Ranchos', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Fernando (Chalatenango)', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Francisco Lempa', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Francisco Morazán', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Ignacio', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Isidro Labrador', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Las Flores', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Luis del Carmen', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Miguel de Mercedes', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Rafael', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Rita', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tejutla', 1, 5)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Cojutepeque', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Candelaria', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Carmen (Cuscatlán)', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Rosario (Cuscatlán)', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Monte San Juan', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Oratorio de Concepción', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Bartolomé Perulapía', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Cristóbal', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San José Guayabal', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Pedro Perulapán', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Rafael Cedros', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Ramón', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Cruz Analquito', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Cruz Michapa', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Suchitoto', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tenancingo', 1, 7)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Aguilares', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Apopa', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ayutuxtepeque', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Cuscatancingo', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ciudad Delgado', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Paisnal', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Guazapa', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ilopango', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Mejicanos', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Nejapa', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Panchimalco', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Rosario de Mora', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Marcos', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Martín', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Salvador', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santiago Texacuangos', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santo Tomás', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Soyapango', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tonacatepeque', 1, 6)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Zacatecoluca', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Cuyultitán', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'El Rosario (La Paz)', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jerusalén', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Mercedes La Ceiba', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Olocuilta', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Paraíso de Osorio', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Antonio Masahuat', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Emigdio', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Francisco Chinameca', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Pedro Masahuat', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Juan Nonualco', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Juan Talpa', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Juan Tepezontes', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Luis La Herradura', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Luis Talpa', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Miguel Tepezontes', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Pedro Nonualco', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Rafael Obrajuelo', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa María Ostuma', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santiago Nonualco', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tapalhuaca', 1, 8)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Cinquera', 1, 9)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Dolores', 1, 9)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Guacotecti', 1, 9)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Ilobasco', 1, 9)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Jutiapa', 1, 9)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Isidro (Cabañas)', 1, 9)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Sensuntepeque', 1, 9)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tejutepeque', 1, 9)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Victoria', 1, 9)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Apastepeque', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Guadalupe', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Cayetano Istepeque', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Esteban Catarina', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Ildefonso', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Lorenzo (San Vicente)', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Sebastián', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'San Vicente', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santa Clara', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Santo Domingo', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tecoluca', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Tepetitán', 1, 10)
INSERT INTO Municipios(nombre, baja, idDepartamento) VALUES (N'Verapaz', 1, 10)




INSERT [dbo].[Grupos] ([nombre], [fundacion], [grupoNum], [horario], [baja], [idDistrito], [idLocalidad], [fechaRegistro], [registrado]) VALUES (N'N/A', CAST(N'1999-01-01' AS Date), 0, N'N/A', 0, 1, 1, CAST(N'1999-01-01' AS Date), 0)

INSERT [dbo].[Domicilios] ([calleNumero], [colonia], [codigoPostal], [baja], [idMunicipio], [entreCalles], [referencia], [contacto], [telefono]) VALUES (N'N/A', N'N/A', N'N/A', 0000, 1, 1, N'N/A', N'N/A', N'N/A', N'N/A')

INSERT [dbo].[Miembros] ([cum], [nombre], [paterno], [materno], [baja], [idSeccion], [idGrupo], [fotoFileName], [fechaNacimiento], [sexo], [particular], [oficina], [movil], [email], [ocupación], [observación], [idDomicilio], [idReligion], [idEscolaridad], [idEstadoCivil]) 
			     VALUES (N'000001', N'root', N'', N'', 1, 1, 1, N'000001.png', CAST(N'1999-01-01' AS Date), N'm', N'', N'', N'', N'', N'', N'', 1, 1, 1, 1)

INSERT [dbo].[Usuarios] ([pass], [estatus], [baja], [idMiembro], [idPerfil]) VALUES (N'd33861eeb1abd03d7527d67206cc0275', 0, 1, 1, 1)