//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegnalUDB.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        public int idAnuncio { get; set; }
        public string mensaje { get; set; }
        public System.DateTime vigencia { get; set; }
        public Nullable<byte> baja { get; set; }
        public int idProvincia { get; set; }
    
        public virtual Provincia Provincia { get; set; }
    }
}
