//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegnalUDB.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Domicilio()
        {
            this.Miembros = new HashSet<Miembro>();
        }
    
        public int idDomicilio { get; set; }
        public string calleNumero { get; set; }
        public string colonia { get; set; }
        public string codigoPostal { get; set; }
        public Nullable<byte> baja { get; set; }
        public int idMunicipio { get; set; }
        public string entreCalles { get; set; }
        public string referencia { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miembro> Miembros { get; set; }
    }
}
