//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegnalUDB.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichasMedica
    {
        public int idFichas { get; set; }
        public int idMiembro { get; set; }
        public string contacto1 { get; set; }
        public string contacto2 { get; set; }
        public string parentesco1 { get; set; }
        public string parentesco2 { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string email { get; set; }
        public string sangre { get; set; }
        public decimal peso { get; set; }
        public decimal estatura { get; set; }
        public string noafilacion { get; set; }
        public bool ss { get; set; }
        public string ssOtro { get; set; }
        public bool piePlano { get; set; }
        public bool ortopedico { get; set; }
        public bool operacion { get; set; }
        public string operacionObs { get; set; }
        public bool limitacion { get; set; }
        public string limitacionObs { get; set; }
        public bool transfusion { get; set; }
        public string transfunsionObs { get; set; }
        public bool alergia { get; set; }
        public string alergiaObs { get; set; }
        public bool cronica { get; set; }
        public string cronicaObs { get; set; }
        public bool tratamiento { get; set; }
        public string tratamientoObs { get; set; }
        public bool Oido { get; set; }
        public string OidoObs { get; set; }
        public bool protesis { get; set; }
        public string protesisObs { get; set; }
        public bool dieta { get; set; }
        public string dietaObs { get; set; }
        public bool tabaco { get; set; }
        public string varcharObs { get; set; }
        public bool vacunacion { get; set; }
        public bool mujer { get; set; }
        public int natacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string imagen { get; set; }
    
        public virtual Miembro Miembro { get; set; }
    }
}
