//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegnalUDB.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichasMedica
    {
        public int idFichas { get; set; }
        public int idMiembro { get; set; }
        public string contacto1 { get; set; }
        public string contacto2 { get; set; }
        public string parentesco1 { get; set; }
        public string parentesco2 { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string email { get; set; }
        public string sangre { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> estatura { get; set; }
        public string noafilacion { get; set; }
        public Nullable<byte> ss { get; set; }
        public string ssOtro { get; set; }
        public string piePlano { get; set; }
        public string ortopedico { get; set; }
        public string operacion { get; set; }
        public string operacionObs { get; set; }
        public string limitacion { get; set; }
        public string limitacionObs { get; set; }
        public string transfusion { get; set; }
        public string transfunsionObs { get; set; }
        public string alergia { get; set; }
        public string alergiaObs { get; set; }
        public string cronica { get; set; }
        public string cronicaObs { get; set; }
        public string tratamiento { get; set; }
        public string tratamientoObs { get; set; }
        public string Oido { get; set; }
        public string OidoObs { get; set; }
        public string protesis { get; set; }
        public string protesisObs { get; set; }
        public string dieta { get; set; }
        public string dietaObs { get; set; }
        public string tabaco { get; set; }
        public string varcharObs { get; set; }
        public string vacunacion { get; set; }
        public string mujer { get; set; }
        public Nullable<byte> natacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string imagen { get; set; }
    
        public virtual Miembro Miembro { get; set; }
    }
}
