//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegnalUDB.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.Miembros = new HashSet<Miembro>();
            this.TotalSeccions = new HashSet<TotalSeccion>();
        }
    
        public int idGrupo { get; set; }
        public string nombre { get; set; }
        public System.DateTime fundacion { get; set; }
        public short grupoNum { get; set; }
        public string horario { get; set; }
        public bool baja { get; set; }
        public int idDistrito { get; set; }
        public int idLocalidad { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public bool registrado { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        public virtual Localidade Localidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Miembro> Miembros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalSeccion> TotalSeccions { get; set; }
    }
}
