//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegnalUDB.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaNegra
    {
        public int idListaNegra { get; set; }
        public string motivo { get; set; }
        public Nullable<int> responsable { get; set; }
        public bool baja { get; set; }
        public Nullable<int> idMiembro { get; set; }
    
        public virtual Miembro Miembro { get; set; }
        public virtual Miembro Miembro1 { get; set; }
    }
}
