//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegnalUDB.Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElSalvadorRegistroScoutsEntities : DbContext
    {
        public ElSalvadorRegistroScoutsEntities()
            : base("name=ElSalvadorRegistroScoutsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anuncio> Anuncios { get; set; }
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Cargo> Cargos { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<Distrito> Distritos { get; set; }
        public virtual DbSet<Domicilio> Domicilios { get; set; }
        public virtual DbSet<Escolaridad> Escolaridads { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivils { get; set; }
        public virtual DbSet<EventoCargo> EventoCargoes { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<EventoSeccion> EventoSeccions { get; set; }
        public virtual DbSet<EventosFuncione> EventosFunciones { get; set; }
        public virtual DbSet<FichasMedica> FichasMedicas { get; set; }
        public virtual DbSet<Funcione> Funciones { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Inscripcione> Inscripciones { get; set; }
        public virtual DbSet<ListaNegra> ListaNegras { get; set; }
        public virtual DbSet<Localidade> Localidades { get; set; }
        public virtual DbSet<MiembroCargo> MiembroCargoes { get; set; }
        public virtual DbSet<MiembroEvento> MiembroEventoes { get; set; }
        public virtual DbSet<MiembroFuncion> MiembroFuncions { get; set; }
        public virtual DbSet<Miembro> Miembros { get; set; }
        public virtual DbSet<Movimiento> Movimientos { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Perfile> Perfiles { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Seccione> Secciones { get; set; }
        public virtual DbSet<TotalSeccion> TotalSeccions { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
