//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegnalUDB.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Miembro()
        {
            this.Bitacoras = new HashSet<Bitacora>();
            this.FichasMedicas = new HashSet<FichasMedica>();
            this.Inscripciones = new HashSet<Inscripcione>();
            this.ListaNegras = new HashSet<ListaNegra>();
            this.ListaNegras1 = new HashSet<ListaNegra>();
            this.MiembroCargoes = new HashSet<MiembroCargo>();
            this.MiembroEventoes = new HashSet<MiembroEvento>();
            this.MiembroFuncions = new HashSet<MiembroFuncion>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int idMiembro { get; set; }
        public string cum { get; set; }
        public string nombre { get; set; }
        public string paterno { get; set; }
        public string materno { get; set; }
        public Nullable<byte> estatus { get; set; }
        public Nullable<byte> baja { get; set; }
        public int idDatoPersonal { get; set; }
        public int idSeccion { get; set; }
        public int idGrupo { get; set; }
        public string fotoFileName { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string sexo { get; set; }
        public string particular { get; set; }
        public string oficina { get; set; }
        public string movil { get; set; }
        public string email { get; set; }
        public string ocupación { get; set; }
        public string observación { get; set; }
        public int idDomicilio { get; set; }
        public int idReligion { get; set; }
        public int idEscolaridad { get; set; }
        public int idEstadoCivil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora> Bitacoras { get; set; }
        public virtual Domicilio Domicilio { get; set; }
        public virtual Escolaridad Escolaridad { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FichasMedica> FichasMedicas { get; set; }
        public virtual Grupos Grupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcione> Inscripciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaNegra> ListaNegras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaNegra> ListaNegras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiembroCargo> MiembroCargoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiembroEvento> MiembroEventoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MiembroFuncion> MiembroFuncions { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual Seccione Seccione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
