//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegnalUDB.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalSeccion
    {
        public int idTotalSeccion { get; set; }
        public Nullable<int> lobeznas { get; set; }
        public Nullable<int> scoutFemeninos { get; set; }
        public Nullable<int> caminanteFemeninos { get; set; }
        public Nullable<int> roverFemeninos { get; set; }
        public Nullable<int> lobatos { get; set; }
        public Nullable<int> scoutMasculinos { get; set; }
        public Nullable<int> caminanteMasculinos { get; set; }
        public Nullable<int> roverMasculinos { get; set; }
        public Nullable<int> scouter { get; set; }
        public Nullable<int> dirigente { get; set; }
        public Nullable<int> padreScout { get; set; }
        public int idGrupo { get; set; }
        public Nullable<byte> mes { get; set; }
        public Nullable<short> anio { get; set; }
    
        public virtual Grupos Grupos { get; set; }
    }
}
